# Generated by Django 6.0.3 on 2026-06-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='home_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_tema_match', to='bigCameL.teams'),
        ),
    ]
