# Generated by Django 6.0.3 on 2026-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0003_players_is_overseas'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
