# Generated by Django 6.0.3 on 2026-06-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0004_players_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
