# Generated by Django 6.0.3 on 2026-06-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0005_matches_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_people_capa', models.IntegerField()),
                ('venue_width', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadium_name', to='bigCameL.venues')),
            ],
        ),
    ]
