# Generated by Django 6.0.3 on 2026-06-21 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0006_about_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_type', models.CharField(max_length=24)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_available', models.IntegerField()),
                ('vip', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('s_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_type', to='bigCameL.sittype')),
            ],
        ),
    ]
