# Generated by Django 6.0.3 on 2026-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0006_about_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_venue',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
