# Generated by Django 6.0.3 on 2026-06-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0007_sittype_totalbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sittype',
            name='price',
        ),
        migrations.CreateModel(
            name='SitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_sit', to='bigCameL.sittype')),
            ],
        ),
    ]
