# Generated by Django 6.0.3 on 2026-06-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0008_remove_sittype_price_sitprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_available', models.IntegerField()),
                ('vip', models.IntegerField()),
                ('normal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TotalBooking',
        ),
    ]
