# Generated by Django 6.0.3 on 2026-06-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0009_totalsit_delete_totalbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_booked', models.IntegerField(blank=True, null=True)),
                ('vip', models.IntegerField(blank=True, null=True)),
                ('normal', models.IntegerField(blank=True, null=True)),
                ('sit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit')),
            ],
        ),
    ]
