# Generated by Django 6.0.3 on 2026-06-22 03:01

import bigCameL.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0010_totalbooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=bigCameL.models.TotalSit, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
