# Generated by Django 6.0.3 on 2026-06-22 12:49

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0012_totalbooked_email_totalbooked_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalbooked',
            name='email',
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
