# Generated by Django 6.0.3 on 2026-06-22 13:53

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0014_alter_totalbooked_sit'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbooked',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
