# Generated by Django 6.0.3 on 2026-06-25 09:35

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0016_video_alter_totalbooked_sit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('champs', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(max_length=1500)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ_year', to='bigCameL.champs')),
            ],
        ),
    ]
