# Generated by Django 6.0.3 on 2026-06-26 14:51

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0020_alter_blog_blog_alter_totalbooked_sit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbooked',
            name='normal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='vip',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
