# Generated by Django 6.0.3 on 2026-07-04 04:03

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0022_alter_totalbooked_sit_fam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
        migrations.DeleteModel(
            name='Fam',
        ),
    ]
