# Generated by Django 6.0.3 on 2026-07-03 04:15

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0022_payments_alter_totalbooked_sit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='fam_img')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
