# Generated by Django 6.0.3 on 2026-07-05 09:28

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0026_alter_totalbooked_sit_fanofipl_delete_fams'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_team', models.IntegerField()),
                ('total_matches', models.IntegerField()),
                ('total_venue', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
