# Generated by Django 6.0.3 on 2026-08-05 10:15

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0027_iplmeta_alter_totalbooked_sit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalbooked',
            name='username',
        ),
        migrations.AddField(
            model_name='totalbooked',
            name='user_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
