# Generated by Django 6.0.3 on 2026-08-08 18:09

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0028_remove_totalbooked_username_totalbooked_user_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbooked',
            name='sit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, related_name='sit_book', to='bigCameL.totalsit'),
        ),
    ]
