# Generated by Django 6.0.3 on 2026-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigCameL', '0002_alter_matches_home_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_overseas',
            field=models.BooleanField(default=False),
        ),
    ]
